baseURL = 'https://playerslayer.net/'
languageCode = 'en-us'
title = 'The Moonshroud Realms'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSearch = true
  BookComments = false
  BookSection = '*'

[markup.goldmark.renderer]
  unsafe = true